# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a622c5ffbc579a7719a9f75678ee7230afb3802a302ba8ad37045fc35f8afa97039e0051458c3d7917c71747d5ad0876121b8139a870c147f0b4ac4857566a4d
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
test:
  secret_key_base: bfb188b3e8a447f9ed71f8f0b3cda2d0468a2e90bcc800d77868ca65892669ad4818c199edb7cd929bb812f601687423a2356450a3e16b46595e0e62e3d66707

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
